name: tox
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read # to fetch code (actions/checkout)
env:
  # note that some tools care only for the name, not the value
  FORCE_COLOR: 1
jobs:
  tox:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest-ppc64le] # All OSes pass except Windows because tests need Unix-only fcntl, grp, pwd, etc.
        python-version:
         - "3.8.18"
         - "3.10.13"
         - "3.12.1"
    steps:
      - uses: actions/checkout@v4
      - name: Using Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: requirements_test.txt
          check-latest: true
          architecture: 'ppc64le'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - run: tox -e run-module
      - run: tox -e run-entrypoint
      - run: tox -e py
